### ISSUE TITLE
the hyperlink to the pseudopotential websites are invalid

### ISSUE THREAD

**Issue by Satinelamp** [pritampanda15/Siesta#1]
The following links are invalid.
 http://nninc.cnf.cornell.edu/ (PSF format) 
https://departments.icmab.es/leem/siesta/Databases/Pseudopotentials/periodictable-intro.html (PSF format)

**Comment by pritampanda15** [comment]
The links have been updated!
https://departments.icmab.es/leem/SIESTA_MATERIAL/Databases/Pseudopotentials/periodictable-gga-abinit.html
https://www.simuneatomistics.com/siesta-pro/siesta-pseudos-and-basis-database/
https://nninc.cnf.cornell.edu/dd_search.php?frmxcprox=&frmxctype=&frmspclass=TM
