### ISSUE TITLE
Energy in Bond currents using SISL

### ISSUE THREAD

**Issue by harshiiiiiii** [pritampanda15/Siesta#2]
Whenever I try to extract bond currents from .nc file, A energy is required to fill in "bond_current(elec, E, kavg=True, isc=None, only='out', orbitals=None, uc=False)"  I don't understand what this Energy means? Please help me resolve it. 
Additional information about the system - The system has a 0.65 eV band gap. When plotting transmission, the first peak on the right side of transmission lies at E = 0.075 eV and the second peak at E = 0.405 eV.
Thanks in advance

**Comment by pritampanda15** [comment]
This issue is related to SISL. Please ask in the SISL forum.  https://github.com/zerothi/sisl/issues
